/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 V1_BLACK.glb --transform 
Files: V1_BLACK.glb [121.25MB] > C:\Users\Robert\Downloads\Revuelto\V1_BLACK-transformed.glb [10.46MB] (91%)
*/

import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/V1_BLACK-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Aerodynamic_door_fin.geometry}
        material={materials["Aerodynamic door fin in Carbon"]}
      />
      <mesh
        geometry={nodes.Lower_exterior_carbon_package.geometry}
        material={materials["Lower exterior carbon package"]}
      />
      <mesh
        geometry={nodes.Upper_exterior_carbon_package.geometry}
        material={materials["Lower exterior carbon package"]}
      />
      <mesh
        geometry={nodes["REAR_DIFFUSER_(ARENA_2024_VERSION)_right"].geometry}
        material={materials["rear diffuser"]}
        rotation={[0, 0, -Math.PI]}
        scale={-1}
      />
      <mesh
        geometry={nodes.Mesh001.geometry}
        material={materials["Glass.002"]}
      />
      <mesh
        geometry={nodes.Mesh001_1.geometry}
        material={materials["E_gMEXX_Aircooler_Metal_Combs.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_2.geometry}
        material={materials["E_gGLXX_Default_Glass_BlinkerMilkyRough.003"]}
      />
      <mesh
        geometry={nodes.Mesh001_3.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        geometry={nodes.Mesh001_4.geometry}
        material={materials["E_gLOXX_Default_NameplateRevueltoBlack.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_5.geometry}
        material={materials["I_gCHXX_Default_Metal_ChromeGlossy.002"]}
      />
      <mesh
        geometry={nodes.Mesh001_6.geometry}
        material={materials["I_gCHXX_Default_Metal_ChromeGlossy.003"]}
      />
      <mesh
        geometry={nodes.Mesh001_7.geometry}
        material={materials["I_E34_DoorPanels_DoorHandles_Trimcolor.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_8.geometry}
        material={materials["I_x_Cockpit_Cluster_Trim_Trimcolor.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_9.geometry}
        material={
          materials["I_A52_LowerDashboard_UpperPartDetail_Trimcolor.001"]
        }
      />
      <mesh
        geometry={nodes.Mesh001_10.geometry}
        material={materials["I_x_Cockpit_Infotainment_Trim_Trimcolor.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_11.geometry}
        material={materials["E_gMEXX_Default_Metal_BrakesHub.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_12.geometry}
        material={materials["E_gRUXX_Default_TireTreadContact.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_13.geometry}
        material={materials["E_gRUXX_TireSidewallFront_Trimcolor.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_14.geometry}
        material={materials["E_x_Wheels_BrakeCaliperLogo_Trim_Trimcolor.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_15.geometry}
        material={materials["E_gRUXX_TireSidewallRear_Trimcolor.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_16.geometry}
        material={materials["Glass.003"]}
      />
      <mesh
        geometry={nodes.Mesh001_17.geometry}
        material={materials["E_gGLXX_Default_Glass_BlinkerMilkyRough.005"]}
      />
      <mesh
        geometry={nodes.Mesh001_18.geometry}
        material={materials.PaletteMaterial005}
      />
      <mesh
        geometry={nodes.Mesh001_19.geometry}
        material={materials["E_x_Wheels_RimFinish_Trim_Trimcolor.004"]}
      />
      <mesh
        geometry={nodes.Mesh001_20.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        geometry={nodes.Mesh001_21.geometry}
        material={materials["E_gRUXX_Default_Rubber_Black.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_22.geometry}
        material={materials["E_gCBXX_Default_Carbon_ShinyExt.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_23.geometry}
        material={materials["E_gLOXX_Default_Logo_Gold.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_24.geometry}
        material={materials.PaletteMaterial002}
      />
      <mesh
        geometry={nodes.Mesh001_25.geometry}
        material={materials["E_gLOXX_Default_Logo_White.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_26.geometry}
        material={materials["E_gLOXX_Default_Logo_Red.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_27.geometry}
        material={materials["E_gLOXX_Default_Logo_Green.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_28.geometry}
        material={materials["REAR BUMPER"]}
      />
      <mesh
        geometry={nodes.Mesh001_29.geometry}
        material={materials.PaletteMaterial004}
      />
      <mesh
        geometry={nodes.Mesh001_30.geometry}
        material={
          materials["I_B61_TunnelConsole_CentralArmrestUpper_Trimcolor.001"]
        }
      />
      <mesh
        geometry={nodes.Mesh001_31.geometry}
        material={
          materials[
            "I_B64_TunnelConsole_CentralArmrestSidesStitch_Trimcolor.001"
          ]
        }
      />
      <mesh
        geometry={nodes.Mesh001_32.geometry}
        material={materials["I_B73_PaintedFlap_PaintedFlap_Trimcolor.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_33.geometry}
        material={
          materials["I_B70_TunnelConsole_TunnelSidesFrontPart_Trimcolor.001"]
        }
      />
      <mesh
        geometry={nodes.Mesh001_34.geometry}
        material={
          materials["I_B65_TunnelConsole_UpperTunnelSidesStitch_Trimcolor.001"]
        }
      />
      <mesh
        geometry={nodes.Mesh001_35.geometry}
        material={materials["I_G26_Seats_MiddleBolster_Trimcolor.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_36.geometry}
        material={
          materials["I_I41_I46_SteeringWheel_SidesStitch_Trimcolor.001"]
        }
      />
      <mesh
        geometry={nodes.Mesh001_37.geometry}
        material={materials["I_A55_UpperDashboard_FrameStitch_Trimcolor.001"]}
      />
      <mesh
        geometry={nodes.Mesh001_38.geometry}
        material={materials["E_x_Wheels_BrakeCaliper_Trim_Trimcolor.001"]}
      />
      <mesh
        geometry={nodes.Mesh002.geometry}
        material={materials["car color"]}
      />
      <mesh
        geometry={nodes.Mesh002_1.geometry}
        material={materials["car  front part"]}
      />
    </group>
  );
}

useGLTF.preload("/V1_BLACK-transformed.glb");

export default Model;
