/* eslint-disable react/no-unknown-property */
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/LAMBORGHINI_REVUELTO4.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409.geometry}
        material={materials["E_gGLXX_Default_Glass_BlinkerMilkyRough.005"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_1.geometry}
        material={materials["Glass.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_2.geometry}
        material={materials["E_gRUXX_TireSidewallRear_Trimcolor.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_3.geometry}
        material={materials["E_x_Wheels_BrakeCaliperLogo_Trim_Trimcolor.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_4.geometry}
        material={materials["E_gRUXX_TireSidewallFront_Trimcolor.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_5.geometry}
        material={materials["E_gRUXX_Default_TireTreadContact.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_6.geometry}
        material={materials["E_gMEXX_Default_Metal_BrakesHub.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_7.geometry}
        material={materials["I_x_Cockpit_Infotainment_Trim_Trimcolor.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_8.geometry}
        material={
          materials["I_A52_LowerDashboard_UpperPartDetail_Trimcolor.001"]
        }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_9.geometry}
        material={materials["I_x_Cockpit_Cluster_Trim_Trimcolor.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_10.geometry}
        material={materials["I_E34_DoorPanels_DoorHandles_Trimcolor.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_11.geometry}
        material={materials["I_gCHXX_Default_Metal_ChromeGlossy.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_12.geometry}
        material={materials["I_gCHXX_Default_Metal_ChromeGlossy.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_13.geometry}
        material={materials["E_gLOXX_Default_NameplateRevueltoBlack.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_14.geometry}
        material={materials["E_gGLXX_Default_Glass_BlinkerMilkyRough.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_15.geometry}
        material={materials["E_gMEXX_Aircooler_Metal_Combs.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_16.geometry}
        material={materials["Glass.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_17.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_18.geometry}
        material={materials["E_x_Wheels_RimFinish_Trim_Trimcolor.003"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_19.geometry}
        material={materials.PaletteMaterial002}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_20.geometry}
        material={materials["E_gMEXX_Default_Metal_BrakesBlack.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_21.geometry}
        material={materials.PaletteMaterial003}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_22.geometry}
        material={materials["I_F20_FloorMats_FloorMatsStitch_Trimcolor.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_23.geometry}
        material={materials["I_F20_FloorMats_FloorMatsPiping_Trimcolor.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_24.geometry}
        material={materials["I_x_Cockpit_PaddleShifters_Trim_Trimcolor.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_25.geometry}
        material={
          materials["I_A58_LowerDashboard_DashboardStripe_Trimcolor.001"]
        }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_26.geometry}
        material={
          materials["I_A58_LowerDashboard_DashboardStripeStitch_Trimcolor.001"]
        }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_27.geometry}
        material={
          materials["I_A51_LowerDashboard_UpperPartStitch_Trimcolor.001"]
        }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_28.geometry}
        material={materials["I_A53_UpperDashboard_EdgesStitch_Trimcolor.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_29.geometry}
        material={materials["I_I45_SteeringWheel_Marker_Trimcolor.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_30.geometry}
        material={materials["I_I44_SteeringWheel_CentralPart_Trimcolor.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_31.geometry}
        material={materials["I_gLOXX_Default_Logo_Green.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_32.geometry}
        material={materials["I_gLOXX_Default_Logo_White.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_33.geometry}
        material={materials["I_gLOXX_Default_Logo_Red.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_34.geometry}
        material={materials["I_gRUXX_Default_Rubber_Black.001"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh409_35.geometry}
        material={materials["I_gLOXX_Default_Logo_Gold.001"]}
      />
    </group>
  );
}

useGLTF.preload("/LAMBORGHINI_REVUELTO4.glb");

export default Model;
